package com.tev.book_a_meal.Common

import com.tev.book_a_meal.Model.Order
import com.tev.book_a_meal.Remote.APIService
import com.tev.book_a_meal.Remote.FCMRetrofitClient
import com.tev.book_a_meal.Remote.IGeoCoordinates
import com.tev.book_a_meal.Remote.RetrofitClient
import android.net.ConnectivityManager
import android.net.NetworkInfo
import android.graphics.Bitmap
import org.json.JSONObject
import org.json.JSONArray
import com.google.android.gms.maps.model.LatLng
import org.json.JSONException
import android.content.ContextWrapper
import android.app.NotificationManager
import android.annotation.TargetApi
import android.os.Build
import android.app.NotificationChannel
import com.tev.book_a_meal.Helper.NotificationHelper
import android.app.PendingIntent
import com.tev.book_a_meal.R
import retrofit2.http.POST
import com.tev.book_a_meal.Model.Sender
import com.tev.book_a_meal.Model.MyResponse
import retrofit2.Retrofit
import retrofit2.converter.scalars.ScalarsConverterFactory
import retrofit2.http.GET
import retrofit2.converter.gson.GsonConverterFactory
import com.google.firebase.iid.FirebaseInstanceIdService
import com.google.firebase.iid.FirebaseInstanceId
import com.google.firebase.database.FirebaseDatabase
import com.google.firebase.database.DatabaseReference
import com.google.firebase.messaging.FirebaseMessagingService
import com.google.firebase.messaging.RemoteMessage
import android.content.Intent
import com.tev.book_a_meal.OrderStatus
import android.media.RingtoneManager
import com.tev.book_a_meal.MainActivity
import android.support.v7.app.AppCompatActivity
import android.support.design.widget.NavigationView
import com.google.firebase.storage.FirebaseStorage
import com.google.firebase.storage.StorageReference
import com.firebase.ui.database.FirebaseRecyclerAdapter
import com.tev.book_a_meal.ViewHolder.MenuViewHolder
import android.support.v7.widget.RecyclerView
import com.rengwuxian.materialedittext.MaterialEditText
import info.hoang8f.widget.FButton
import androidx.core.widget.DrawerLayout
import uk.co.chrisjenx.calligraphy.CalligraphyContextWrapper
import android.os.Bundle
import uk.co.chrisjenx.calligraphy.CalligraphyConfig
import android.support.design.widget.FloatingActionButton
import android.support.v7.widget.LinearLayoutManager
import android.view.LayoutInflater
import android.content.DialogInterface
import android.support.design.widget.Snackbar
import android.app.Activity
import android.app.ProgressDialog
import android.content.Context
import com.google.android.gms.tasks.OnSuccessListener
import com.google.android.gms.tasks.OnFailureListener
import com.google.firebase.storage.OnProgressListener
import com.firebase.ui.database.FirebaseRecyclerOptions
import com.squareup.picasso.Picasso
import com.tev.book_a_meal.Interface.ItemClickListener
import com.tev.book_a_meal.FoodList
import android.view.ViewGroup
import androidx.core.view.GravityCompat
import com.tev.book_a_meal.BannerActivity
import com.tev.book_a_meal.SendMessage
import com.tev.book_a_meal.ScrollingActivity
import com.google.firebase.database.ValueEventListener
import com.google.firebase.database.DataSnapshot
import com.google.firebase.database.DatabaseError
import android.view.View.OnCreateContextMenuListener
import android.view.ContextMenu
import android.view.ContextMenu.ContextMenuInfo
import com.tev.book_a_meal.ViewHolder.MyViewHolder
import com.tev.book_a_meal.Model.Food
import com.tev.book_a_meal.ViewHolder.FoodViewHolder
import com.tev.book_a_meal.ViewHolder.OrderDetailAdapter
import com.tev.book_a_meal.ViewHolder.OrderViewHolder
import com.jaredrummler.materialspinner.MaterialSpinner
import com.tev.book_a_meal.OrderDetail
import com.tev.book_a_meal.TrackingOrder
import android.text.TextUtils
import com.tev.book_a_meal.ViewHolder.ShowCommentViewHolder
import androidx.core.widget.SwipeRefreshLayout
import androidx.core.widget.SwipeRefreshLayout.OnRefreshListener
import com.tev.book_a_meal.Common.NumberOfFood
import com.tev.book_a_meal.SignInAsStaff
import com.tev.book_a_meal.SignInAsAdmin
import com.tev.book_a_meal.ViewHolder.UserViewHolder
import android.text.InputType
import android.text.method.PasswordTransformationMethod
import com.tev.book_a_meal.MainAdminActivity
import com.tev.book_a_meal.Home
import androidx.core.app.FragmentActivity
import com.google.android.gms.maps.OnMapReadyCallback
import com.google.android.gms.common.api.GoogleApiClient.ConnectionCallbacks
import com.google.android.gms.common.api.GoogleApiClient.OnConnectionFailedListener
import com.google.android.gms.maps.GoogleMap
import com.google.android.gms.common.api.GoogleApiClient
import androidx.core.app.ActivityCompat
import android.content.pm.PackageManager
import com.google.android.gms.location.LocationServices
import com.google.android.gms.maps.SupportMapFragment
import com.google.android.gms.maps.model.MarkerOptions
import com.google.android.gms.maps.CameraUpdateFactory
import android.graphics.BitmapFactory
import com.google.android.gms.maps.model.BitmapDescriptorFactory
import com.tev.book_a_meal.TrackingOrder.ParserTask
import kotlin.jvm.Synchronized
import com.google.android.gms.common.GooglePlayServicesUtil
import com.google.android.gms.common.ConnectionResult
import android.os.AsyncTask
import android.view.View
import android.widget.*
import com.com.tev.book_a_meal.Common.DirectionJSONParser
import com.google.android.gms.maps.model.PolylineOptions
import com.com.tev.book_a_meal.Model.Banner
import com.tev.book_a_meal.ViewHolder.BannerViewHolder
import com.google.android.gms.tasks.OnCompleteListener
import com.tev.book_a_meal.ManageAccount
import com.tev.book_a_meal.ViewComment
import com.tev.book_a_meal.ShipperManagement
import com.tev.book_a_meal.AdminScrollingActivity
import com.tev.book_a_meal.Model.Shipper
import com.tev.book_a_meal.ViewHolder.ShipperViewHolder

object NumberOfFood {
    fun convertIdToName(code: String): String? {
        return if (code == "1") "1-Pc Cheesy Chicken Rice" else if (code == "2") "1-Pc Chicken Rice" else if (code == "3") "2-Pc Cheesy Chicken Rice" else if (code == "4") "2-Pc Chicken Rice" else if (code == "5") "1-Pc Chicken Porridge" else if (code == "6") "2-Pc Meal" else if (code == "7") "3-Pc Meal" else if (code == "8") "Half-Spring Chicken Meal" else if (code == "9") "6-Pcs Chicken Nuggets Meal" else if (code == "10") "Single Cheesy Burger Set Meal" else if (code == "11") "Single Premium Burger Set Meal" else if (code == "12") "Double Cheesy Burger Set Meal" else if (code == "13") "Double Premium Burger Set Meal" else if (code == "14") "Full-Spring Chicken Meal" else if (code == "15") "2 Person Combo" else if (code == "16") "3 Person Combo" else if (code == "17") "5 Person Combo" else if (code == "18") "Potato Platter (L)" else if (code == "19") "Criss Cut Fries (L)" else if (code == "20") "Borenos Rice" else if (code == "21") "Cheesy Wedges (L)" else if (code == "22") "Chicken Porridge" else if (code == "23") "Mashed Potato (L)" else if (code == "24") "3 Pc Fried Buns" else if (code == "25") "Coleslaw (L)" else if (code == "26") "Chicken Nuggets (6-Pcs)" else if (code == "27") "Chicken Nuggets (10-Pcs)" else if (code == "28") "Chicken Nuggets (21-Pcs)" else if (code == "29") "Borenos Sauce" else if (code == "30") "Cheese Dip" else if (code == "31") "Tartar Sauce" else if (code == "32") "Onion Sour Cream Sauce" else if (code == "33") "1-Pc Chicken" else if (code == "34") "2-Pc Chicken" else if (code == "35") "3-Pc Chicken" else if (code == "36") "5-Pc Chicken" else if (code == "37") "9-Pc Chicken" else if (code == "38") "15-Pc Chicken" else if (code == "39") "Full Spring A La Carte" else if (code == "40") "Coca Cola Tin" else if (code == "41") "Ice Lemon Tea Tin" else if (code == "42") "Passionfruit Tea Tin" else if (code == "43") "Ayataka Green Tea Tin" else if (code == "44") "Sprite Bottle (1.5L)" else if (code == "45") "Coca Cola Bottle (1.5L)" else if (code == "46") "AL 5 (Promo) - 5 Pc Chicken" else null
    }
}